import pytest

from nbahl.common.constants import GameLogNBAApiSourceConstants
from nbahl.common.enums import (
    LeagueID,
    PlayerOrTeamAbbreviation,
    SeasonTypeAllStar,
)


@pytest.mark.parametrize(
    "league_id, player_or_team_abbreviation, season_type, expected_source_name",
    [
        (
            LeagueID.NBA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.REGULAR_SEASON,
            "league-game-logs-00-t-regular-season",
        ),
        (
            LeagueID.NBA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.PRE_SEASON,
            "league-game-logs-00-t-pre-season",
        ),
        (
            LeagueID.NBA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.PLAYOFFS,
            "league-game-logs-00-t-playoffs",
        ),
        (
            LeagueID.NBA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.ALL_STAR,
            "league-game-logs-00-t-all-star",
        ),
        (
            LeagueID.NBA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.REGULAR_SEASON,
            "league-game-logs-00-p-regular-season",
        ),
        (
            LeagueID.NBA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.PRE_SEASON,
            "league-game-logs-00-p-pre-season",
        ),
        (
            LeagueID.NBA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.PLAYOFFS,
            "league-game-logs-00-p-playoffs",
        ),
        (
            LeagueID.NBA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.ALL_STAR,
            "league-game-logs-00-p-all-star",
        ),
        (
            LeagueID.ABA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.REGULAR_SEASON,
            "league-game-logs-01-t-regular-season",
        ),
        (
            LeagueID.ABA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.PRE_SEASON,
            "league-game-logs-01-t-pre-season",
        ),
        (
            LeagueID.ABA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.PLAYOFFS,
            "league-game-logs-01-t-playoffs",
        ),
        (
            LeagueID.ABA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.ALL_STAR,
            "league-game-logs-01-t-all-star",
        ),
        (
            LeagueID.ABA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.REGULAR_SEASON,
            "league-game-logs-01-p-regular-season",
        ),
        (
            LeagueID.ABA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.PRE_SEASON,
            "league-game-logs-01-p-pre-season",
        ),
        (
            LeagueID.ABA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.PLAYOFFS,
            "league-game-logs-01-p-playoffs",
        ),
        (
            LeagueID.ABA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.ALL_STAR,
            "league-game-logs-01-p-all-star",
        ),
        (
            LeagueID.G_LEAGUE,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.REGULAR_SEASON,
            "league-game-logs-20-t-regular-season",
        ),
        (
            LeagueID.G_LEAGUE,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.PRE_SEASON,
            "league-game-logs-20-t-pre-season",
        ),
        (
            LeagueID.G_LEAGUE,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.PLAYOFFS,
            "league-game-logs-20-t-playoffs",
        ),
        (
            LeagueID.G_LEAGUE,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.ALL_STAR,
            "league-game-logs-20-t-all-star",
        ),
        (
            LeagueID.G_LEAGUE,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.REGULAR_SEASON,
            "league-game-logs-20-p-regular-season",
        ),
        (
            LeagueID.G_LEAGUE,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.PRE_SEASON,
            "league-game-logs-20-p-pre-season",
        ),
        (
            LeagueID.G_LEAGUE,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.PLAYOFFS,
            "league-game-logs-20-p-playoffs",
        ),
        (
            LeagueID.G_LEAGUE,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.ALL_STAR,
            "league-game-logs-20-p-all-star",
        ),
        (
            LeagueID.WNBA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.REGULAR_SEASON,
            "league-game-logs-10-t-regular-season",
        ),
        (
            LeagueID.WNBA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.PRE_SEASON,
            "league-game-logs-10-t-pre-season",
        ),
        (
            LeagueID.WNBA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.PLAYOFFS,
            "league-game-logs-10-t-playoffs",
        ),
        (
            LeagueID.WNBA,
            PlayerOrTeamAbbreviation.TEAM,
            SeasonTypeAllStar.ALL_STAR,
            "league-game-logs-10-t-all-star",
        ),
        (
            LeagueID.WNBA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.REGULAR_SEASON,
            "league-game-logs-10-p-regular-season",
        ),
        (
            LeagueID.WNBA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.PRE_SEASON,
            "league-game-logs-10-p-pre-season",
        ),
        (
            LeagueID.WNBA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.PLAYOFFS,
            "league-game-logs-10-p-playoffs",
        ),
        (
            LeagueID.WNBA,
            PlayerOrTeamAbbreviation.PLAYER,
            SeasonTypeAllStar.ALL_STAR,
            "league-game-logs-10-p-all-star",
        ),
    ],
)
def test_get_source_name(
    league_game_log_constants: GameLogNBAApiSourceConstants,
    league_id: LeagueID,
    player_or_team_abbreviation: PlayerOrTeamAbbreviation,
    season_type: SeasonTypeAllStar,
    expected_source_name: str,
) -> None:
    source_name = league_game_log_constants.get_source_name(
        league_id=league_id,
        player_or_team_abbreviation=player_or_team_abbreviation,
        season_type=season_type,
    )

    assert source_name == expected_source_name
